@echo off
echo Starting Python Backend...
start cmd /k "cd PythonBackend && python app.py"
echo Waiting for Python backend to initialize...
timeout /t 5
echo Starting Java Web Application...
start cmd /k "cd JavaWebApp && mvn spring-boot:run"
echo Waiting for Java Web Application to initialize...
timeout /t 10
echo Both services are now running!
echo Opening web application in your default browser...
start http://localhost:8080
echo If the page doesn't load correctly, wait a few more seconds and refresh.